"""delete all attributes from tasks table.

Revision ID: 38b923aed5af
Revises: 078f55293274
Create Date: 2024-11-14 14:08:49.500813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38b923aed5af'
down_revision: Union[str, None] = '078f55293274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'longitude')
    op.drop_column('tasks', 'dispatcher_name')
    op.drop_column('tasks', 'planner_date')
    op.drop_column('tasks', 'latitude')
    op.drop_column('tasks', 'work_type')
    op.drop_column('tasks', 'photo_url_2')
    op.drop_column('tasks', 'code')
    op.drop_column('tasks', 'location')
    op.drop_column('tasks', 'comments')
    op.drop_column('tasks', 'completion_date')
    op.drop_column('tasks', 'voltage_class')
    op.drop_column('tasks', 'photo_url_1')
    op.drop_column('tasks', 'supervisor')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('supervisor', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('photo_url_1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('voltage_class', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('completion_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('comments', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('photo_url_2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('work_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('planner_date', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('dispatcher_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
