"""Add comments field to Task

Revision ID: 7becc7906068
Revises: 659446da1831
Create Date: 2024-11-07 04:45:44.502545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7becc7906068'
down_revision: Union[str, None] = '659446da1831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('comments', sa.String(), nullable=True))
    op.alter_column('tasks', 'completion_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'completion_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('tasks', 'comments')
    # ### end Alembic commands ###
