"""Link Task to User and remove supervisor

Revision ID: bfa8118ca98f
Revises: 4f4d720f518c
Create Date: 2025-06-11 16:26:57.037495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfa8118ca98f'
down_revision: Union[str, None] = '4f4d720f518c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('worker_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'users', ['worker_id'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'worker_id')
    # ### end Alembic commands ###
