"""Remove uuid4() foncion..

Revision ID: d660bdc0b082
Revises: 5be6f6c07f6a
Create Date: 2024-12-16 08:20:09.266580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd660bdc0b082'
down_revision: Union[str, None] = '5be6f6c07f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
