"""Add all fields.

Revision ID: e122c9010ba3
Revises: 38b923aed5af
Create Date: 2024-11-14 14:10:33.119475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e122c9010ba3'
down_revision: Union[str, None] = '38b923aed5af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('code', sa.String(), nullable=False))
    op.add_column('tasks', sa.Column('dispatcher_name', sa.String(), nullable=False))
    op.add_column('tasks', sa.Column('location', sa.String(), nullable=False))
    op.add_column('tasks', sa.Column('planner_date', sa.String(), nullable=False))
    op.add_column('tasks', sa.Column('work_type', sa.String(), nullable=False))
    op.add_column('tasks', sa.Column('completion_date', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('voltage_class', sa.Float(), nullable=False))
    op.add_column('tasks', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('photo_url_1', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('photo_url_2', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('comments', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('supervisor', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'supervisor')
    op.drop_column('tasks', 'comments')
    op.drop_column('tasks', 'photo_url_2')
    op.drop_column('tasks', 'photo_url_1')
    op.drop_column('tasks', 'longitude')
    op.drop_column('tasks', 'latitude')
    op.drop_column('tasks', 'voltage_class')
    op.drop_column('tasks', 'completion_date')
    op.drop_column('tasks', 'work_type')
    op.drop_column('tasks', 'planner_date')
    op.drop_column('tasks', 'location')
    op.drop_column('tasks', 'dispatcher_name')
    op.drop_column('tasks', 'code')
    # ### end Alembic commands ###
