"""Link Task to worktype and voltage and remove work_type_id

Revision ID: f9b85e3dd3ee
Revises: bfa8118ca98f
Create Date: 2025-06-11 19:00:40.452311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9b85e3dd3ee'
down_revision: Union[str, None] = 'bfa8118ca98f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('work_type', sa.VARCHAR(), nullable=True))
    op.add_column('tasks', sa.Column('voltage', sa.Float(), nullable=True))
    op.alter_column('tasks', 'worker_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_tasks_worker_id'), 'tasks', ['worker_id'], unique=False)
    op.drop_constraint('tasks_work_type_id_fkey', 'tasks', type_='foreignkey')
    op.drop_constraint('tasks_voltage_id_fkey', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'work_type_id')
    op.drop_column('tasks', 'voltage_id')
    # op.drop_column('tasks', 'supervisor')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('supervisor', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('voltage_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('work_type_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('tasks_voltage_id_fkey', 'tasks', 'voltages', ['voltage_id'], ['uid'])
    op.create_foreign_key('tasks_work_type_id_fkey', 'tasks', 'work_types', ['work_type_id'], ['uid'])
    op.drop_index(op.f('ix_tasks_worker_id'), table_name='tasks')
    op.alter_column('tasks', 'worker_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('tasks', 'voltage')
    op.drop_column('tasks', 'work_type')
    # ### end Alembic commands ###
